### PR TITLE
Refactor CrashDelegate

### PR DESCRIPTION
**Pull request by chrwend**
This branch is not ready for merging, yet. I still have to add some tests, but feel free to do a first review.

### CODE REVIEW

**Comment by lukasspiess** [comment]
@chrwend Which release are you planning this for? 1.0-beta.1?

**Comment by anlinde** [comment]
Why do you implement a protocol for a specific manager in the generic manager class?

**Comment by lukasspiess** [comment]
I merged `develop` into this branch so we get a meaningful diff here ob Github.
Otherwise, this branch still lacks the appropriate unit tests for the delegate methods.

**Comment by lukasspiess** [comment]
We will probably abandon this branch and start from scratch.

**Pull request closed without merging**
