### PR TITLE
Add nullability warnings introduced with Xcode 6.3

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds backwards compatible warnings which warn the developer about passing `nil` as a parameter where she shouldn't do that.

### CODE REVIEW

**Comment by lukasspiess** [comment]
Please hold of with merging this pull request until Xcode 6.3 is actually released.

**Comment by anlinde** [comment]
Will this then still compile when using Xcode 6.2? You need to make sure it does.

**Comment by lukasspiess** [comment]
@anlinde Yes, see here: https://github.com/Microsoft/AppInsights-iOS/commit/aebe54d37779fe64c9456a9a162ea898b7453d41

**Comment by lukasspiess** [comment]
No changes with 6.3b4

**Comment by lukasspiess** [comment]
Xcode 6.3 has now been released, we can merge this.

**Comment by chrwend** [comment]
@lukasspiess: I get a few errors when I try to build the test app with xCode 6.2

**Comment by lukasspiess** [comment]
@chrwend Could you please check again and let me know what you think about putting the macros in the umbrella header? Let me know if you can think of a better place. Thanks!

**Pull request merged**
