### PR TITLE
Add developer mode

### PR DESCRIPTION
**Pull request by lukasspiess**

### CODE REVIEW

**Comment by lukasspiess** [comment]
We should check if some parts of the documentation need updates for this

**Comment by TroubleMakerBen** [comment]
@Lukas I added the API for the developer mode. Please have a look. Your stuff was ready to merge imho, so please just review my commit and merge :)

**Comment by lukasspiess** [comment]
@TroubleMakerBen As discussed last week, "developer mode" does not equal automatic debug logging. Debug logging still should have to be enabled manually and only the modified batch sized should take effect.

**Comment by TroubleMakerBen** [comment]
@lukasspiess sorry. Android does it differently ;) – so should I revert and use a 2nd property?

**Pull request merged**
