### PR TITLE
Extend automatic lifecycle tracking

### PR DESCRIPTION
**Pull request by ghost**
This adds automatic tracking of interesting app lifecycle events like backgrounding, foregrounding and cold app starts.

- [x] Add observers to `disableAutoLifecycleTracking` switch
- [ ] Add tests for foreground, background, app start?

### CODE REVIEW

**Comment by lukasspiess** [comment]
@scsouthw What do you think about this? Especially the naming of the events and adding the device orientation as a property.

**Comment by TroubleMakerBen** [comment]
We have to wait with this until we have switched to Schema 2.1 and have a context field for this. The approach to send as custom event has unwanted side-effects (a lot of custom events showing up in the user's portal)

**Comment by scsouthw** [comment]
@TroubleMakerBen thanks for following up with PMs on this. We should keep the ability to detect orientation changes but we won't have a good way to capture the data until the schema 2.1 update.

**Comment by lukasspiess** [comment]
@TroubleMakerBen @scsouthw I'll leave pretty much everything in place, just remove the actual `track..` calls

**Pull request closed without merging**
