### PR TITLE
Enable debug logging by default during development

### PR DESCRIPTION
**Pull request by lukasspiess**
This enables debug logging by default when the SDK is run on the simulator or with a debug configuration

### CODE REVIEW

**Comment by lukasspiess** [comment]
I would argue that this makes it harder to see _really_ important error messages that always get logged. With a lot of debug noise they might get lost.

**Comment by anlinde** [comment]
Please make sure to document the debug case, that it only applies when also the SDK is build from source. The debug case does not work when using the binary distribution.

**Comment by lukasspiess** [comment]
@ashtom What exactly is the value you want to get from by default enabled debug logging? Is there any specific case you want to cover with this?
Our debug logging is actually very verbose and we log messages for common errors (wrong order of calls, missing instrumentation key, etc.) anyways, no matter if you're in debug mode or not.

**Comment by anlinde** [comment]
The SDK has some default logging using NSLog, and a lot of detailed logging that is enabled with the `DebugLogEnabled` property for all components. This will cause log output every few seconds when the app is running. I don't think it is a good default experience for anytime when developing an app and running it in the simulator or using the DEBUG configuration (doesn't work with binary distribution anyway).

I would favour a way that shows more log data when actually integrating the SDK, but then turned off. When developing an app I want to see my apps log data, not lot of SDK log data. There is also no easy filtering in the debug console in Xcode.

**Comment by lukasspiess** [comment]
@JakubOleksy Can we maybe get a more specific definition of what you want to achieve with the "developer mode" so we can discuss what the best technical solution is to that? Thanks!

**Comment by lukasspiess** [comment]
Okay, I just talked to Jakub. We'll not enable debug logging by default for now.

**Pull request closed without merging**
